Mailbox/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('list/', include('list.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

list/urls.py
from django.urls import path
from list.views import LetterListView, LetterCreateView, LetterUpdateView, LetterDeleteView

app_name = 'list'

urlpatterns = [
    path('', LetterListView.as_view(), name = 'list'),
    path('add_letter/', LetterCreateView.as_view(), name = 'add_letter'),
    path('update/<int:pk>/', LetterUpdateView.as_view(), name = 'update'),
    path('delete/<int:pk>/', LetterDeleteView.as_view(), name = 'delete'),
]

list/models.py
from django.db import models

class Letter(models.Model):
    title = models.CharField(max_length=100)
    contents = models.CharField(max_length=1000)
    image = models.ImageField(blank=True, upload_to='list/%Y/%m/%d/')

    def __str__(self):
        return f'제목: {self.title}, 내용: {self.contents}'

list/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from list.models import Letter


class LetterListView(ListView):
    model = Letter

class LetterCreateView(CreateView):
    model = Letter
    fields = '__all__' #['title', 'contents', 'image']
    template_name = 'list/letter_create.html'
    success_url = reverse_lazy('list:list')

class LetterUpdateView(UpdateView):
    model = Letter
    fields = '__all__'
    template_name_suffix = '_update' #drink_update.html
    success_url = reverse_lazy('list:list')

class LetterDeleteView(DeleteView):
    model = Letter
    success_url = reverse_lazy('list:list')

list/templates/list/letter_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Letter Confirm Delete</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ letter }} <br>
    해당 편지를 삭제하시겠습니까?
    <button type = "submit"> Add</button>
    <button type = "button" onclick="history.back()">Cancel</button>
</form>
</body>
</html>

list/templates/list/letter_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Letter Create</title>
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type = "submit"> Add</button>
    <button type = "button" onclick="history.back()">Cancel</button>
</form>
</body>
</html>

list/templates/list/letter_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Letter List</title>
</head>
<a>
<table>
    <thead>
    <tr>
        <th>#</th>
        <th>image</th>
        <th>title</th>
        <th>Modify</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for letter in letter_list %}
    <tr>
        <td>{{ forloop.counter }}</td>
           {% if letter.image != '' %}
        <td><img src = "{{ letter.image.url }}" alt = "" style = "height:88px"></td>
            {% else %}<td>----</td>
        {% endif %}
        <td>{{ letter }}</td>
        <td><a href = "{% url 'list:update' pk=letter.id %}">Modify</a></td>
        <td><a href = "{% url 'list:delete' pk=letter.id %}">Delete</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<a href = "{% url 'list:add_letter' %}">Add Letter</a>
</body>
</html>

list/templates/list/letter_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Letter Update</title>
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type = "submit"> Add</button>
    <button type = "button" onclick="history.back()">Cancel</button>
</form>
</body>
</html>